apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend
  namespace: duploservices-argocd01
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: demo-project

  source:
    # IMPORTANT: Replace with your Git repository URL
    repoURL: https://github.com/dspaxton/argo-sample.git
    targetRevision: HEAD
    path: base/frontend

  destination:
    server: https://kubernetes.default.svc
    namespace: duploservices-darren

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
